apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Default
  - ../../apps/kube-ops-view.yaml
  - ../../apps/compliance-operator.yaml

# Hub
  - ../../apps/acm-operator.yaml
  - ../../apps/acm-configuration.yaml

# Virt
  - ../../apps/openshift-virtualization-operator.yaml
  - ../../apps/openshift-virtualization-instance.yaml
  - ../../apps/mtv-operator.yaml
  - ../../apps/mtv-configuration.yaml
