apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - appprojects.yaml
  - compliance-operator-app.yaml
  - external-secrets-operator-app.yaml  
  - openshift-virtualization-instance-app.yaml
