apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - appprojects.yaml
  - cluster-config/cluster-config-app.yaml
  - acm/acm-operator-app.yaml
  - acm/acm-instance-app.yaml
  - openshift-virtualization/openshift-virtualization-instance-app.yaml
  - openshift-virtualization/openshift-virtualization-operator-app.yaml
# - compliance/compliance-operator-app.yaml
# - external-secrets/external-secrets-operator-app.yaml
  - node-health/node-health-operators-app.yaml
  - node-health/node-health-instance-app.yaml

