apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - appprojects.yaml
  - cluster-standards-app.yaml
  - acm-operator-app.yaml
  - acm-instance-app.yaml



  # - compliance-operator-app.yaml
  # - openshift-virtualization-instance-app.yaml
  # - openshift-virtualization-operator-app.yaml
  # - node-health-operators-app.yaml
  # - node-health-instances-app.yaml

