apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
# Use subscription or OperatorPolicy
  - nhc-operator-policy.yaml
#  - nhc-operator-subscription.yaml

# Additional operators
#  - far-operator-policy.yaml
#  - nm-operator-policy.yaml
#  - snr-operator-policy.yaml