apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - far-operator-policy.yaml
# Use subscription instead of OperatorPolicy
#  - nhc-operator-policy.yaml
  - nhc-operator.yaml
  - nm-operator-policy.yaml
  - snr-operator-policy.yaml