apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:  
  name: descheduler-configuration
  namespace: openshift-gitops
  labels:
    appgrp: day2
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:    
    server: https://kubernetes.default.svc
  project: virt
  source:
    path: components/descheduler-configuration
    repoURL: https://github.com/mmwillingham/gitops-standards-repo
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true